modLoader="javafml"
loaderVersion="[38,)"
license="${mod_license}"
issueTrackerURL="${mod_issues}"

[[mods]]
modId="${mod_id}"
version="${file.jarVersion}"
displayName="${mod_name}"
displayURL="${mod_homepage}"
credits="This project is made possible with Patreon support from players like you. Thank you! ${mod_supporters}"
authors="${mod_author}"
description='''
${mod_description}
'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
