modLoader = "javafml"
loaderVersion = "[42,)"
license = "${mod_license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
modId = "${mod_id}"
updateJSONURL="https://updates.blamejared.com/get?n=${mod_id}&gv=${minecraft_version}"
version = "${file.jarVersion}"
displayName = "${mod_name}"
displayURL = "${mod_homepage}"
credits = "This project is made possible with Patreon support from players like you. Thank you! ${mod_supporters}"
authors = "${mod_author}"
description = '''
${mod_description}
'''

[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[42,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${ mod_id }]]
modId = "bookshelf"
mandatory = true
versionRange = "[15,)"
ordering = "NONE"
side = "CLIENT"